# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive' 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -U pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse_linux_x86_64
        path: |
          dist/*.whl
