# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build doc2vecc_prebuilt wheels

on:
  release:
    types: [created]
  workflow_dispatch:
  
env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TWINE_REPOSITORY_URL: ${{ secrets.PYPI_SERVER }}
  TWINE_NON_INTERACTIVE: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive' 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -U pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        cat <<EOF > setup.cfg
        [bdist_wheel]
        universal = false
        plat-name=manylinux1_x86_64
        EOF
        cat setup.cfg
        make wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse_manylinux1_x86_64
        path: |
          dist/*.whl
    - name: Upload to PyPi server
      run: |
        twine upload dist/*
    
          
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive' 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -U pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        make wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse_mac
        path: |
          dist/*.whl
    - name: Upload to PyPi server
      run: |
        twine upload dist/*
